-- CreateEnum
CREATE TYPE "Role" AS ENUM ('APPLICANT', 'CONTRACTOR', 'TEAM_LEAD', 'QUARTERMASTER', 'QUARTERMASTER_ADMIN', 'ADMIN');

-- AlterTable
ALTER TABLE "User" ADD COLUMN     "role" "Role" NOT NULL DEFAULT 'APPLICANT';
